<?php

namespace ContainerM6p8p04;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZcfgSnSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zcfgSnS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zcfgSnS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AdminController::index' => ['privates', '.service_locator.QUl9icC', 'get_ServiceLocator_QUl9icCService', true],
            'App\\Controller\\AdminController::supprimer' => ['privates', '.service_locator.TQA.DQ.', 'get_ServiceLocator_TQA_DQ_Service', true],
            'App\\Controller\\ClientController::nouveau' => ['privates', '.service_locator.ddnXYXj', 'get_ServiceLocator_DdnXYXjService', true],
            'App\\Controller\\ClientController::supprimer' => ['privates', '.service_locator.ddnXYXj', 'get_ServiceLocator_DdnXYXjService', true],
            'App\\Controller\\MessageController::index' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\SmarketingController::ajouterClient' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\AdminController:index' => ['privates', '.service_locator.QUl9icC', 'get_ServiceLocator_QUl9icCService', true],
            'App\\Controller\\AdminController:supprimer' => ['privates', '.service_locator.TQA.DQ.', 'get_ServiceLocator_TQA_DQ_Service', true],
            'App\\Controller\\ClientController:nouveau' => ['privates', '.service_locator.ddnXYXj', 'get_ServiceLocator_DdnXYXjService', true],
            'App\\Controller\\ClientController:supprimer' => ['privates', '.service_locator.ddnXYXj', 'get_ServiceLocator_DdnXYXjService', true],
            'App\\Controller\\MessageController:index' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\SmarketingController:ajouterClient' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\AdminController::index' => '?',
            'App\\Controller\\AdminController::supprimer' => '?',
            'App\\Controller\\ClientController::nouveau' => '?',
            'App\\Controller\\ClientController::supprimer' => '?',
            'App\\Controller\\MessageController::index' => '?',
            'App\\Controller\\SmarketingController::ajouterClient' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AdminController:index' => '?',
            'App\\Controller\\AdminController:supprimer' => '?',
            'App\\Controller\\ClientController:nouveau' => '?',
            'App\\Controller\\ClientController:supprimer' => '?',
            'App\\Controller\\MessageController:index' => '?',
            'App\\Controller\\SmarketingController:ajouterClient' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
