<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM6p8p04\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM6p8p04/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerM6p8p04.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerM6p8p04\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerM6p8p04\App_KernelDevDebugContainer([
    'container.build_hash' => 'M6p8p04',
    'container.build_id' => '153ef75b',
    'container.build_time' => 1610649702,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM6p8p04');
