<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'admin' => [[], ['_controller' => 'App\\Controller\\AdminController::index'], [], [['text', '/admin']], [], []],
    'admin-editing' => [['id'], ['_controller' => 'App\\Controller\\AdminController::index'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/admin']], [], []],
    'sup-admin' => [['id'], ['_controller' => 'App\\Controller\\AdminController::supprimer'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'id', true], ['text', '/admin']], [], []],
    'client' => [[], ['_controller' => 'App\\Controller\\ClientController::nouveau'], [], [['text', '/client']], [], []],
    'client-editing' => [['id'], ['_controller' => 'App\\Controller\\ClientController::nouveau'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/client']], [], []],
    'supprimer' => [['id'], ['_controller' => 'App\\Controller\\ClientController::supprimer'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'id', true], ['text', '/client']], [], []],
    'message' => [[], ['_controller' => 'App\\Controller\\MessageController::index'], [], [['text', '/message']], [], []],
    'login1' => [[], ['_controller' => 'App\\Controller\\SmarketingController::login'], [], [['text', '/']], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\SmarketingController::login'], [], [['text', '/login/']], [], []],
    'logout' => [[], ['_controller' => 'App\\Controller\\SmarketingController::logout'], [], [['text', '/deconnexion']], [], []],
    'nouveau-client' => [[], ['_controller' => 'App\\Controller\\SmarketingController::nouveauClient'], [], [['text', '/nouveau-client']], [], []],
    'mes-clients' => [[], ['_controller' => 'App\\Controller\\SmarketingController::mesClients'], [], [['text', '/mes-clients']], [], []],
    'administrateurs' => [[], ['_controller' => 'App\\Controller\\SmarketingController::mesAdmins'], [], [['text', '/administrateurs']], [], []],
    'historiques' => [[], ['_controller' => 'App\\Controller\\SmarketingController::historiques'], [], [['text', '/historiques']], [], []],
    'ajouter-client' => [[], ['_controller' => 'App\\Controller\\SmarketingController::ajouterClient'], [], [['text', '/ajouter-client']], [], []],
    'parametres' => [[], ['_controller' => 'App\\Controller\\SmarketingController::parametres'], [], [['text', '/parametres']], [], []],
];
